/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mega mix (https://sketchfab.com/oscar3dmodel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/morgana-persona-5-tactica-ea2666bad3cc4a22af4a6732768bd14c
Title: morgana (persona 5 tactica)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Morg(props) {
  const { nodes, materials } = useGLTF('/models/morgana.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_15.geometry}
          material={materials.MI_Unit_ModelOutline}
          skeleton={nodes.Object_15.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_16.geometry}
          material={materials.MI_Unit_ModelOutline}
          skeleton={nodes.Object_16.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_18.geometry}
          material={materials.MI_PC0003_M00_Fa}
          skeleton={nodes.Object_18.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_20.geometry}
          material={materials.MI_PC0003_M07_Fa}
          skeleton={nodes.Object_20.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_22.geometry}
          material={materials.MI_PC0003_M11_Fa}
          skeleton={nodes.Object_22.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_23.geometry}
          material={materials.MI_PC0003_M12_Fa}
          skeleton={nodes.Object_23.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_24.geometry}
          material={materials.MI_PC0003_M13_Fa}
          skeleton={nodes.Object_24.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_25.geometry}
          material={materials.MI_PC0003_M18_Fa}
          skeleton={nodes.Object_25.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_26.geometry}
          material={materials.MI_PC0003_C101}
          skeleton={nodes.Object_26.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_27.geometry}
          material={materials.MI_PC0003_F101}
          skeleton={nodes.Object_27.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_28.geometry}
          material={materials.MI_Unit_Outline}
          skeleton={nodes.Object_28.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_29.geometry}
          material={materials.MI_Unit_Outline}
          skeleton={nodes.Object_29.skeleton}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Obj_Eye00_MI_PC0003_E00_L_0.geometry}
          material={materials.MI_PC0003_E00_L}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Obj_Eye00_MI_PC0003_E00_R_0.geometry}
          material={materials.MI_PC0003_E00_R}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Obj_Eye08_MI_PC0003_E08_Fa_0.geometry}
          material={materials.MI_PC0003_E08_Fa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Obj_Eye09_MI_PC0003_E09_Fa_0.geometry}
          material={materials.MI_PC0003_E09_Fa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Obj_Eyelid00_MI_PC0003_E50_0.geometry}
          material={materials.MI_PC0003_E50}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/morgana.glb")